### ISSUE TITLE
Design logo for the project 

### ISSUE THREAD

**Issue by Akilan1999** [HWTechClub/Custom-Static-Website-Generator#15]
The project needs a logo to be designed.

**Comment by mk210** [comment]
Hey @Akilan1999 Can i know more about the project? There seem to be multiple project folders

**Comment by Akilan1999** [comment]
Hi @mk210,
This project is just a custom static website generator like Hugo. There is just a Whatsapp bot designed as a type of interaction to the project.

**Comment by mk210** [comment]
Oh okay! So, you want a logo for the WhatsApp bot project yeah? @Akilan1999

**Comment by mk210** [comment]
@Akilan1999 What do you think about them? I like the White logo, but what do you say?
![whatsapp bot logo ideas](https://user-images.githubusercontent.com/55575735/122669626-53d78200-d1cf-11eb-8e42-9301411247a1.png)

**Comment by Akilan1999** [comment]
The project is not based on whatsapp

**Comment by Akilan1999** [comment]
We can this here https://github.com/HWTechClub/Custom-Static-Website-Generator/tree/master/whatsapp-web.js as a README file

**Comment by Akilan1999** [comment]
But the project is nothing related to whatsapp

**Comment by mk210** [comment]
I don't understand. This project is a Static website generator bot **deployed on WhatsApp** yeah? I might be wrong, can you explain what the project is please?

**Comment by mk210** [comment]
Hey @Akilan1999, I made a logo design for the custom website generator. I made the multiple versions of the logos depending upon the device which will access the wesbite. Lmk what you think of them!
![CustomWebsiteGenerator-Logo ideas](https://user-images.githubusercontent.com/55575735/123397859-f5861700-d5b3-11eb-8ea8-df0ae77eb41e.png)

**Comment by Akilan1999** [comment]
This looks great !

**Comment by Akilan1999** [comment]
You can add both the whatsapp image and this logo in README file and create a pull request

**Comment by mk210** [comment]
I have created a pull request, you may merge it after reviewing the README.md file in my branch.
